# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goignore < Formula
  desc "Easy gitignore files from the command line"
  homepage "https://github.com/FollowTheProcess/goignore"
  version "0.3.4"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FollowTheProcess/goignore/releases/download/v0.3.4/goignore_0.3.4_Darwin_x86_64.tar.gz"
      sha256 "a7f2a7b35b8e67cb0d43700436b5aca474e7f28c753f823f5003390677a88987"
    end
    if Hardware::CPU.arm?
      url "https://github.com/FollowTheProcess/goignore/releases/download/v0.3.4/goignore_0.3.4_Darwin_arm64.tar.gz"
      sha256 "b5ed45a12c2240699e65bd0a3b669ea8f9fb009a5c2733a9015f18919b22f0dd"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/FollowTheProcess/goignore/releases/download/v0.3.4/goignore_0.3.4_Linux_x86_64.tar.gz"
      sha256 "6b694b7b8499772a3001d4acc384157cac7e5eab1fcffc7967eec8b6f16415b3"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FollowTheProcess/goignore/releases/download/v0.3.4/goignore_0.3.4_Linux_arm64.tar.gz"
      sha256 "6c89217c0176af647c5261101ccd97b39ec040575c45d01a8267bf0b1afdf111"
    end
  end

  def install
    bin.install "goignore"
  end

  test do
    "#{bin}/goignore --version"
  end
end
