# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goignore < Formula
  desc "Easy gitignores from the command line."
  homepage "https://github.com/FollowTheProcess/goignore"
  version "0.4.0"
  license "MIT License"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FollowTheProcess/goignore/releases/download/v0.4.0/goignore_0.4.0_Darwin_x86_64.tar.gz"
      sha256 "3f29e1ca7b3534e182504affc80f35b473449cfba168ed4af71ad10e2bec83cf"

      def install
        bin.install "goignore"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FollowTheProcess/goignore/releases/download/v0.4.0/goignore_0.4.0_Darwin_arm64.tar.gz"
      sha256 "e2eeb556f3c03dad77851119bc7275cc71f45db550a78afcae9d626b763804aa"

      def install
        bin.install "goignore"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FollowTheProcess/goignore/releases/download/v0.4.0/goignore_0.4.0_Linux_arm64.tar.gz"
      sha256 "c1697ece4f623f6f3b5898791f98454a4072069e3416aadfa2d5d128bae14b16"

      def install
        bin.install "goignore"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/FollowTheProcess/goignore/releases/download/v0.4.0/goignore_0.4.0_Linux_x86_64.tar.gz"
      sha256 "ed6d9c4d5994dea03db68ba9dc4cfa6bd11a74aea4b7acdec7e6762d98649f0a"

      def install
        bin.install "goignore"
      end
    end
  end

  test do
    "#{bin}/goignore version"
  end
end
