# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gotoil < Formula
  desc "Handy CLI to automate the development workflow"
  homepage "https://github.com/FollowTheProcess/gotoil"
  version "0.1.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FollowTheProcess/gotoil/releases/download/v0.1.2/gotoil_0.1.2_Darwin_x86_64.tar.gz"
      sha256 "75aa4929b21adb7b0b4784abd437adf89129ff1e96be3b42395504d99182913e"

      def install
        bin.install "gotoil"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FollowTheProcess/gotoil/releases/download/v0.1.2/gotoil_0.1.2_Darwin_arm64.tar.gz"
      sha256 "70869fede7c83e02f1996b47ea86f7f2febdcdd1257d81490ac114becd00da28"

      def install
        bin.install "gotoil"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FollowTheProcess/gotoil/releases/download/v0.1.2/gotoil_0.1.2_Linux_arm64.tar.gz"
      sha256 "11db14e7748c10c0703c570b3987426a05b995c3746a53a19bd7ca83ffb71d39"

      def install
        bin.install "gotoil"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/FollowTheProcess/gotoil/releases/download/v0.1.2/gotoil_0.1.2_Linux_x86_64.tar.gz"
      sha256 "461a1f16fdf4d2aef021276ccbf5298902edd1323d517db2faec87a87520fcbc"

      def install
        bin.install "gotoil"
      end
    end
  end

  depends_on "git"

  test do
    "#{bin}/gotoil version"
  end
end
