# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Py < Formula
  desc "Approximate port of Brett Cannon's python-launcher to Go."
  homepage "https://github.com/FollowTheProcess/py"
  version "0.3.0"
  license "MIT License"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FollowTheProcess/py/releases/download/v0.3.0/py_0.3.0_Darwin_x86_64.tar.gz"
      sha256 "c4e020bfb4b67d4ed038359c8788c22c16f39f89b1bfe24440316d76dfb6cf78"

      def install
        bin.install "py"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FollowTheProcess/py/releases/download/v0.3.0/py_0.3.0_Darwin_arm64.tar.gz"
      sha256 "35a8b89b44bf92584bbcd7b0a6aa8873f9eda47982d058c5fd4603a700c7bd02"

      def install
        bin.install "py"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FollowTheProcess/py/releases/download/v0.3.0/py_0.3.0_Linux_arm64.tar.gz"
      sha256 "99f9d188865dca5c60b4eb634666f7b7d33113056561e9c24e8350811b5673d5"

      def install
        bin.install "py"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/FollowTheProcess/py/releases/download/v0.3.0/py_0.3.0_Linux_x86_64.tar.gz"
      sha256 "44a42b5f3b22327f9d93447a35a7aeac0bd278118af9017b481f9276a0a46058"

      def install
        bin.install "py"
      end
    end
  end

  conflicts_with "python-launcher"

  test do
    "#{bin}/py --version"
  end
end
