# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Py < Formula
  desc "Approximate port of Brett Cannon's python-launcher to Go."
  homepage "https://github.com/FollowTheProcess/py"
  version "0.1.5"
  license "MIT License"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/FollowTheProcess/py/releases/download/v0.1.5/py_0.1.5_Darwin_arm64.tar.gz"
      sha256 "24a58697bc162707c499ea34ca79bca3b215d44832a773030140a7036d54e935"

      def install
        bin.install "py"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/FollowTheProcess/py/releases/download/v0.1.5/py_0.1.5_Darwin_x86_64.tar.gz"
      sha256 "eab8c455b741f48e4e64567ad62db03ba9b02a602ffced10e16dc1deb9d0d253"

      def install
        bin.install "py"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FollowTheProcess/py/releases/download/v0.1.5/py_0.1.5_Linux_arm64.tar.gz"
      sha256 "94c2fbce803c82da7a4b39b0b9682cf6af9a95383a47d0bed543d9016e31ac1f"

      def install
        bin.install "py"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/FollowTheProcess/py/releases/download/v0.1.5/py_0.1.5_Linux_x86_64.tar.gz"
      sha256 "0fde3d8445d4bdafd929764f165df92a687f20fef6f94dc946ca10fd6b3f6113"

      def install
        bin.install "py"
      end
    end
  end

  conflicts_with "python-launcher"

  test do
    "#{bin}/py --version"
  end
end
