# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spok < Formula
  desc "It's a build system Jim, but not as we know it!"
  homepage "https://github.com/FollowTheProcess/spok"
  version "0.1.0"
  license "Apache Software License 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/FollowTheProcess/spok/releases/download/v0.1.0/spok_0.1.0_Darwin_arm64.tar.gz"
      sha256 "0670ad51b4b08b6b7535bc652ed7700d1373879b87971bd24b1ebbaf2b4c480e"

      def install
        bin.install "spok"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/FollowTheProcess/spok/releases/download/v0.1.0/spok_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "fd0bc515ec9af018c2934635903101f4ff1076bb9e48e70dff68a7d99505a336"

      def install
        bin.install "spok"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FollowTheProcess/spok/releases/download/v0.1.0/spok_0.1.0_Linux_arm64.tar.gz"
      sha256 "b1fa07fdb6efc1a8fdefedc94b6615e6b7ee19eeb8c040a9bacacefa33c35a0e"

      def install
        bin.install "spok"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/FollowTheProcess/spok/releases/download/v0.1.0/spok_0.1.0_Linux_x86_64.tar.gz"
      sha256 "c3b7069648c20202678e4a9d9c5eda80b6132dc2d912f22bacdf687c8a2484ac"

      def install
        bin.install "spok"
      end
    end
  end

  test do
    "#{bin}/spok --version"
  end
end
