# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tag < Formula
  desc "Interact with semver git tags with ease!"
  homepage "https://github.com/FollowTheProcess/tag"
  version "0.1.3"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FollowTheProcess/tag/releases/download/v0.1.3/tag_0.1.3_Darwin_x86_64.tar.gz"
      sha256 "21a1d31bee209f32e733549fd36ae7ddafb4ecc6b10294e16e2b81b2573bcca2"
    end
    if Hardware::CPU.arm?
      url "https://github.com/FollowTheProcess/tag/releases/download/v0.1.3/tag_0.1.3_Darwin_arm64.tar.gz"
      sha256 "f6024380c8d64052219c44ef2188c054629faa4e5715deb32945a6c629c8120e"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/FollowTheProcess/tag/releases/download/v0.1.3/tag_0.1.3_Linux_x86_64.tar.gz"
      sha256 "8cf970b8087704e5b0e803f3489735455c63c85e43d084a0e31ada3404939d4e"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FollowTheProcess/tag/releases/download/v0.1.3/tag_0.1.3_Linux_arm64.tar.gz"
      sha256 "839fe9ee5c9edfa9ad993f5a44a16efca8034fef51d287a7542eee8793fc3dae"
    end
  end

  def install
    bin.install "tag"
  end

  test do
    "#{bin}/tag version"
  end
end
