# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Venv < Formula
  desc "CLI to take the pain out of python virtual environments."
  homepage "https://github.com/FollowTheProcess/venv"
  version "0.3.0"
  license "Apache Software License 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FollowTheProcess/venv/releases/download/v0.3.0/venv_0.3.0_Darwin_x86_64.tar.gz"
      sha256 "b0f720fbf0faa597d81f5a4bacdd20b3b9e9daaa8be807213305201e53fb2926"

      def install
        bin.install "venv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FollowTheProcess/venv/releases/download/v0.3.0/venv_0.3.0_Darwin_arm64.tar.gz"
      sha256 "64abe9f145645e859863ee039f9503493383f172ec464b5c91b7e4c06347e7a8"

      def install
        bin.install "venv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/FollowTheProcess/venv/releases/download/v0.3.0/venv_0.3.0_Linux_x86_64.tar.gz"
      sha256 "0260d1acad74e0e3b3ebcbb3611fd7ec68281306f979b5b096f35e4354c578a8"

      def install
        bin.install "venv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FollowTheProcess/venv/releases/download/v0.3.0/venv_0.3.0_Linux_arm64.tar.gz"
      sha256 "c7c9714209f4834d835f7f3159458f0ed685aa0da1cb8c3ac457003dfcc97a94"

      def install
        bin.install "venv"
      end
    end
  end

  test do
    "#{bin}/venv --version"
  end
end
