# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Venv < Formula
  desc "CLI to take the pain out of python virtual environments."
  homepage "https://github.com/FollowTheProcess/venv"
  version "0.1.3"
  license "Apache Software License 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FollowTheProcess/venv/releases/download/v0.1.3/venv_0.1.3_Darwin_x86_64.tar.gz"
      sha256 "399e08a15065301cd222cef0d1f5157220db4e5a2f7d0a1dee1aa9df618c3b5b"

      def install
        bin.install "venv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FollowTheProcess/venv/releases/download/v0.1.3/venv_0.1.3_Darwin_arm64.tar.gz"
      sha256 "8b1e847dae85b33556e995e55059fcdb8db75eaee80437208badaad4db60b1a8"

      def install
        bin.install "venv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FollowTheProcess/venv/releases/download/v0.1.3/venv_0.1.3_Linux_arm64.tar.gz"
      sha256 "3c5f2c9aed3fe95dbf71f1ebb141031d2788b698ae983a952af86ada5b42d7a8"

      def install
        bin.install "venv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/FollowTheProcess/venv/releases/download/v0.1.3/venv_0.1.3_Linux_x86_64.tar.gz"
      sha256 "8de51089a75cc6faa42a78a34579ac7da886a7795ced1bafd3059d99c22bb7e3"

      def install
        bin.install "venv"
      end
    end
  end

  test do
    "#{bin}/venv --version"
  end
end
