# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Venv < Formula
  desc "CLI to take the pain out of python virtual environments."
  homepage "https://github.com/FollowTheProcess/venv"
  version "0.1.1"
  license "Apache Software License 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/FollowTheProcess/venv/releases/download/v0.1.1/venv_0.1.1_Darwin_arm64.tar.gz"
      sha256 "926a7c5cdbd3511b6f909787be5f43913b513374947b84c39bd3b7e26df53cfb"

      def install
        bin.install "venv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/FollowTheProcess/venv/releases/download/v0.1.1/venv_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "b02676ff0c423f0a3e02227976908b172904ff4b21ae938d060067e09cdd900e"

      def install
        bin.install "venv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FollowTheProcess/venv/releases/download/v0.1.1/venv_0.1.1_Linux_arm64.tar.gz"
      sha256 "9c6392d7f9215c438318d7f84e1fbded79f2bbc4e8c98a2b68cd43db4336c76d"

      def install
        bin.install "venv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/FollowTheProcess/venv/releases/download/v0.1.1/venv_0.1.1_Linux_x86_64.tar.gz"
      sha256 "5840ed1fc8930d9818679949e3bd96439c946972f018e8b4ffe9880e3c0cf23e"

      def install
        bin.install "venv"
      end
    end
  end

  test do
    "#{bin}/venv --version"
  end
end
