# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-rekt" do
  desc "A profoundly unhelpful git extension"
  homepage "https://github.com/FollowTheProcess/git-rekt"
  version "0.3.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-rekt"

  on_macos do
    on_intel do
      url "https://github.com/FollowTheProcess/git-rekt/releases/download/v0.3.1/git-rekt-0.3.1-darwin-x86_64.tar.gz"
      sha256 "fa72760069b13bf7a8cfeaec6d0c110489ab1bb90bf3a115ccab67d2c2399810"
    end
    on_arm do
      url "https://github.com/FollowTheProcess/git-rekt/releases/download/v0.3.1/git-rekt-0.3.1-darwin-arm64.tar.gz"
      sha256 "8e8144af72a2dae1a76aed04ce9d1ab19e5fdf620ded1fd700483955b5827aac"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/FollowTheProcess/git-rekt/releases/download/v0.3.1/git-rekt-0.3.1-linux-x86_64.tar.gz"
      sha256 "1385cc89d02421760be572a47bc9a120c7f9e517ccd1143babd666a07376b7c6"
    end
    on_arm do
      url "https://github.com/FollowTheProcess/git-rekt/releases/download/v0.3.1/git-rekt-0.3.1-linux-arm64.tar.gz"
      sha256 "537b67c655833a7436ea3a06cb895b91519cc49310697ca3360119bedf5c2284"
    end
  end

  conflicts_with formula: [
      "git-rekt",
    ]

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/git-rekt"]
    end
  end

  # No zap stanza required
end
