# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-rekt" do
  desc "A profoundly unhelpful git extension"
  homepage "https://github.com/FollowTheProcess/git-rekt"
  version "0.4.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-rekt"

  on_macos do
    on_intel do
      url "https://github.com/FollowTheProcess/git-rekt/releases/download/v0.4.1/git-rekt-0.4.1-darwin-x86_64.tar.gz"
      sha256 "1c1eb4f0f956d2fa819042bd5d17aa734c3b7fb3e33321d893824399c97952a6"
    end
    on_arm do
      url "https://github.com/FollowTheProcess/git-rekt/releases/download/v0.4.1/git-rekt-0.4.1-darwin-arm64.tar.gz"
      sha256 "6943b68f39e1d006f9f5cbb1eba6ddef41e4b8b594d371910077f74661387227"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/FollowTheProcess/git-rekt/releases/download/v0.4.1/git-rekt-0.4.1-linux-x86_64.tar.gz"
      sha256 "0019e5086f68b65776ab56c5906ceaaa3e996eafead9d3694227cf7e2bbdfa1e"
    end
    on_arm do
      url "https://github.com/FollowTheProcess/git-rekt/releases/download/v0.4.1/git-rekt-0.4.1-linux-arm64.tar.gz"
      sha256 "21cee05f8615fe476abb136f2e334ee303a2dff76c9e12dc50523c92eabae51a"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/git-rekt"]
    end
  end

  # No zap stanza required
end
