# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-rekt" do
  desc "A profoundly unhelpful git extension"
  homepage "https://github.com/FollowTheProcess/git-rekt"
  version "0.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-rekt"

  on_macos do
    on_intel do
      url "https://github.com/FollowTheProcess/git-rekt/releases/download/v0.4.0/git-rekt-0.4.0-darwin-x86_64.tar.gz"
      sha256 "137412021947630c727da68f03eff76ebcd8f1d6f8783a2402361770a7229d64"
    end
    on_arm do
      url "https://github.com/FollowTheProcess/git-rekt/releases/download/v0.4.0/git-rekt-0.4.0-darwin-arm64.tar.gz"
      sha256 "a2faf9d5fe1576b13a14bbd951194fdad28e99bb7a1964405b7e8d22839af60c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/FollowTheProcess/git-rekt/releases/download/v0.4.0/git-rekt-0.4.0-linux-x86_64.tar.gz"
      sha256 "7ca135c8922e572be3831fb9e2039d7cc194b90372704b43f34f4bba206cd4e5"
    end
    on_arm do
      url "https://github.com/FollowTheProcess/git-rekt/releases/download/v0.4.0/git-rekt-0.4.0-linux-arm64.tar.gz"
      sha256 "a8aba1a3cdc77a8a48121512d3f5961bf2781df0c6c15af97b1ccdd4d73d7a83"
    end
  end

  conflicts_with formula: [
      "git-rekt",
    ]

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/git-rekt"]
    end
  end

  # No zap stanza required
end
