# This file was generated by GoReleaser. DO NOT EDIT.
cask "goignore" do
  desc "An extremely simple Go CLI to hit the gitignore.io API"
  homepage "https://github.com/FollowTheProcess/goignore"
  version "0.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "goignore"

  on_macos do
    on_intel do
      url "https://github.com/FollowTheProcess/goignore/releases/download/v0.5.0/goignore-0.5.0-darwin-x86_64.tar.gz"
      sha256 "849d50e28b3acd1d693653df13c5172fca2fe33ee7fc0e5fdaab84153ed96d8d"
    end
    on_arm do
      url "https://github.com/FollowTheProcess/goignore/releases/download/v0.5.0/goignore-0.5.0-darwin-arm64.tar.gz"
      sha256 "e4a9c5fd0fde4b1b92f40153126f4187ae856aff22bc5edb51b586893647a97f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/FollowTheProcess/goignore/releases/download/v0.5.0/goignore-0.5.0-linux-x86_64.tar.gz"
      sha256 "334fd05d593c9de19df5831f02bdd8c31fec8e0ac86c51c7cb1010b08cb45dbc"
    end
    on_arm do
      url "https://github.com/FollowTheProcess/goignore/releases/download/v0.5.0/goignore-0.5.0-linux-arm64.tar.gz"
      sha256 "89ec3672bf3adc1e32e371a694d1c2491e9b688912d86cf2038d1c807ad90271"
    end
  end

  conflicts_with formula: [
      "goignore",
    ]

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/goignore"]
    end
  end

  # No zap stanza required
end
