# This file was generated by GoReleaser. DO NOT EDIT.
cask 'goignore' do
  desc 'An extremely simple Go CLI to hit the gitignore.io API'
  homepage 'https://github.com/FollowTheProcess/goignore'
  version '0.5.1'
  deprecate! date: "2025-07-12", because: "This project is no longer supported"

  livecheck do
    skip 'Auto-generated on release.'
  end

  binary 'goignore'

  on_macos do
    on_intel do
      url 'https://github.com/FollowTheProcess/goignore/releases/download/v0.5.1/goignore-0.5.1-darwin-x86_64.tar.gz'
      sha256 'd621b5ae12b588d5ae145495acb55867a7a440a1b88fcc32dd8a42bf24b4b06c'
    end
    on_arm do
      url 'https://github.com/FollowTheProcess/goignore/releases/download/v0.5.1/goignore-0.5.1-darwin-arm64.tar.gz'
      sha256 '1692efad2df4c59bcdb302a232ab254120c00a0c143c0af0eb5560c3c6e527d3'
    end
  end

  on_linux do
    on_intel do
      url 'https://github.com/FollowTheProcess/goignore/releases/download/v0.5.1/goignore-0.5.1-linux-x86_64.tar.gz'
      sha256 '9924be73d697461546ed0568d0554b579bfcdb5e6990a95f091f6225637c7697'
    end
    on_arm do
      url 'https://github.com/FollowTheProcess/goignore/releases/download/v0.5.1/goignore-0.5.1-linux-arm64.tar.gz'
      sha256 'ea2ee8f5d767f477ae97feae6a2a6586d548bbf2b036f55b82d0f943bd970284'
    end
  end

  conflicts_with formula: [
    'goignore'
  ]

  postflight do
    if system_command('/usr/bin/xattr', args: ['-h']).exit_status.zero?
      system_command '/usr/bin/xattr', args: ['-dr', 'com.apple.quarantine', "#{staged_path}/goignore"]
    end
  end

  # No zap stanza required
end
