# This file was generated by GoReleaser. DO NOT EDIT.
cask "goignore" do
  desc "An extremely simple Go CLI to hit the gitignore.io API"
  homepage "https://github.com/FollowTheProcess/goignore"
  version "0.6.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "goignore"

  on_macos do
    on_intel do
      url "https://github.com/FollowTheProcess/goignore/releases/download/v0.6.0/goignore-0.6.0-darwin-x86_64.tar.gz"
      sha256 "77d369f427026375e71bab746fef962bbf3583e54ae30fc56cedf2f6a8c3534a"
    end
    on_arm do
      url "https://github.com/FollowTheProcess/goignore/releases/download/v0.6.0/goignore-0.6.0-darwin-arm64.tar.gz"
      sha256 "a690721e8179d1d72cdca68a2246ed47f93c3b40ea761d3cdd2f03e26adf28ce"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/FollowTheProcess/goignore/releases/download/v0.6.0/goignore-0.6.0-linux-x86_64.tar.gz"
      sha256 "1bec0b4d7188f50c85d466229c6b51f15dd7e668b7de3a2a137be67d877c7bcd"
    end
    on_arm do
      url "https://github.com/FollowTheProcess/goignore/releases/download/v0.6.0/goignore-0.6.0-linux-arm64.tar.gz"
      sha256 "872cebe396539f49d6beac850d12286d5b57a43dbb8591564ee7f04c3a4db590"
    end
  end

  conflicts_with formula: [
      "goignore",
    ]

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/goignore"]
    end
  end

  # No zap stanza required
end
