# This file was generated by GoReleaser. DO NOT EDIT.
cask "gowc" do
  version "0.6.3"

  on_macos do
    on_intel do
      sha256 "42f6c8b5103e7696cc07b46922489eae59444eec7126a7001d34e1330dcb0c1b"
      url "https://get.followtheprocess.codes/gowc/#{version}/gowc-#{version}-darwin-x86_64.tar.gz",
        verified: "github.com/FollowTheProcess/gowc"
    end
    on_arm do
      sha256 "37855cd1a1902a756bf8d75d6292b7bc5c4db7b6a854128e9b23326fefe55f86"
      url "https://get.followtheprocess.codes/gowc/#{version}/gowc-#{version}-darwin-arm64.tar.gz",
        verified: "github.com/FollowTheProcess/gowc"
    end
  end

  on_linux do
    on_intel do
      sha256 "cb987292913822a87fdd1ed885dd30c38f231d837c5dfea8567f549ad647f4f7"
      url "https://get.followtheprocess.codes/gowc/#{version}/gowc-#{version}-linux-x86_64.tar.gz",
        verified: "github.com/FollowTheProcess/gowc"
    end
    on_arm do
      sha256 "a0070145fd123cdcfe04d697adc2aebeea14c12b274b9e06625d7fc75bebd253"
      url "https://get.followtheprocess.codes/gowc/#{version}/gowc-#{version}-linux-arm64.tar.gz",
        verified: "github.com/FollowTheProcess/gowc"
    end
  end

  name "gowc"
  desc "Implementation of wc in Go"
  homepage "https://github.com/FollowTheProcess/gowc"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gowc"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gowc"]
    end
  end

  # No zap stanza required

end
