# This file was generated by GoReleaser. DO NOT EDIT.
cask "gowc" do
  desc "Implementation of wc in Go"
  homepage "https://github.com/FollowTheProcess/gowc"
  version "0.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gowc"

  on_macos do
    on_intel do
      url "https://github.com/FollowTheProcess/gowc/releases/download/v0.5.0/gowc-0.5.0-darwin-x86_64.tar.gz"
      sha256 "ba2730dff3b52d8595ef74593c75048b0806b36be67579d8dd8195942feee2d4"
    end
    on_arm do
      url "https://github.com/FollowTheProcess/gowc/releases/download/v0.5.0/gowc-0.5.0-darwin-arm64.tar.gz"
      sha256 "f8d5f672e6f19da73e171017047ab1b28ab5840ca4e703718e777a87bb790674"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/FollowTheProcess/gowc/releases/download/v0.5.0/gowc-0.5.0-linux-x86_64.tar.gz"
      sha256 "995128cdd1de6a9889b6b4298c6e27079eece98cc438bf3f1e9f82bbf9a90c7f"
    end
    on_arm do
      url "https://github.com/FollowTheProcess/gowc/releases/download/v0.5.0/gowc-0.5.0-linux-arm64.tar.gz"
      sha256 "49e399d6771e8857665f8aa0600ea565318732f8e927f977542dfe1b00cfcd1a"
    end
  end

  conflicts_with formula: [
      "gowc",
    ]

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gowc"]
    end
  end

  # No zap stanza required
end
