# This file was generated by GoReleaser. DO NOT EDIT.
cask "gowc" do
  version "0.6.4"

  on_macos do
    on_intel do
      sha256 "c50b16c75f0fb939ccd69c3899a22a244f849544997e115eade7c19e1a924785"
      url "https://get.followtheprocess.codes/gowc/v#{version}/gowc-#{version}-darwin-x86_64.tar.gz",
        verified: "github.com/FollowTheProcess/gowc"
    end
    on_arm do
      sha256 "fd602757fc7db09b4ee3306bde20472c53562427ad4334b25b9ce5200ea5b428"
      url "https://get.followtheprocess.codes/gowc/v#{version}/gowc-#{version}-darwin-arm64.tar.gz",
        verified: "github.com/FollowTheProcess/gowc"
    end
  end

  on_linux do
    on_intel do
      sha256 "b7dc8ecafa58f154bccfa7a25127dd9baac706310e8f6377493adbae771aeeec"
      url "https://get.followtheprocess.codes/gowc/v#{version}/gowc-#{version}-linux-x86_64.tar.gz",
        verified: "github.com/FollowTheProcess/gowc"
    end
    on_arm do
      sha256 "6a822d821bb4343e5783c10c43dce34a514a26a659d9c2438c6a851a24b58bcb"
      url "https://get.followtheprocess.codes/gowc/v#{version}/gowc-#{version}-linux-arm64.tar.gz",
        verified: "github.com/FollowTheProcess/gowc"
    end
  end

  name "gowc"
  desc "Implementation of wc in Go"
  homepage "https://github.com/FollowTheProcess/gowc"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gowc"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gowc"]
    end
  end

  # No zap stanza required

end
