# This file was generated by GoReleaser. DO NOT EDIT.
cask "spok" do
  desc "It's a build system Jim, but not as we know it!"
  homepage "https://github.com/FollowTheProcess/spok"
  version "0.8.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spok"

  on_macos do
    on_intel do
      url "https://github.com/FollowTheProcess/spok/releases/download/v0.8.0/spok-0.8.0-darwin-x86_64.tar.gz"
      sha256 "df89319639ae761add14871ac6bdd19af34d8a0a31dcab0ad3c72e6527c3e169"
    end
    on_arm do
      url "https://github.com/FollowTheProcess/spok/releases/download/v0.8.0/spok-0.8.0-darwin-arm64.tar.gz"
      sha256 "38264b1bdbbb0bb3fdc0309897aa8bf8d6f881945ab42f91d45aa3c014ff0ae4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/FollowTheProcess/spok/releases/download/v0.8.0/spok-0.8.0-linux-x86_64.tar.gz"
      sha256 "d56c45a19fce3228d4d73a2f8236dd9a08d7edbe8d71599e439a33e7f10a12c6"
    end
    on_arm do
      url "https://github.com/FollowTheProcess/spok/releases/download/v0.8.0/spok-0.8.0-linux-arm64.tar.gz"
      sha256 "6fc9bbe461d424f13b9b7e47b91a45ec66de56ffabbaf503d7ad40cd8e30adf1"
    end
  end

  conflicts_with formula: [
      "spok",
    ]

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/spok"]
    end
  end

  # No zap stanza required
end
