# This file was generated by GoReleaser. DO NOT EDIT.
cask "spok" do
  desc "It's a build system Jim, but not as we know it!"
  homepage "https://github.com/FollowTheProcess/spok"
  version "0.7.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spok"

  on_macos do
    on_intel do
      url "https://github.com/FollowTheProcess/spok/releases/download/v0.7.0/spok-0.7.0-darwin-x86_64.tar.gz"
      sha256 "6dfbee2faf8eb9f1ece7b95d5fbff09cb32d7fd244ca4f76cbb758b13242373f"
    end
    on_arm do
      url "https://github.com/FollowTheProcess/spok/releases/download/v0.7.0/spok-0.7.0-darwin-arm64.tar.gz"
      sha256 "124cfdc4623fb0381549a4c34df3f0a6b322fd51c72b2f45f0cf6e7842f313f0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/FollowTheProcess/spok/releases/download/v0.7.0/spok-0.7.0-linux-x86_64.tar.gz"
      sha256 "e690540353542bd31c7b655160b08ebfdc84ebe5ae6d32d635e3b515770f3886"
    end
    on_arm do
      url "https://github.com/FollowTheProcess/spok/releases/download/v0.7.0/spok-0.7.0-linux-arm64.tar.gz"
      sha256 "0c24a02798e64b926cf55ea40adb7fc91e188fe664188afa0b3aebfb4909ef66"
    end
  end

  conflicts_with formula: [
      "spok",
    ]

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/spok"]
    end
  end

  # No zap stanza required
end
