# This file was generated by GoReleaser. DO NOT EDIT.
cask "spok" do
  desc "It's a build system Jim, but not as we know it!"
  homepage "https://github.com/FollowTheProcess/spok"
  version "0.7.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spok"

  on_macos do
    on_intel do
      url "https://github.com/FollowTheProcess/spok/releases/download/v0.7.1/spok-0.7.1-darwin-x86_64.tar.gz"
      sha256 "e5ddf205937df66ff9aede1b8de13a586b8561efafb06516cc08c3476d3205a7"
    end
    on_arm do
      url "https://github.com/FollowTheProcess/spok/releases/download/v0.7.1/spok-0.7.1-darwin-arm64.tar.gz"
      sha256 "a9d8caea2ee9485df67be656d1d0ee50020300c45542c6f06d96f1426a440ae1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/FollowTheProcess/spok/releases/download/v0.7.1/spok-0.7.1-linux-x86_64.tar.gz"
      sha256 "348343082b0300537a4e7d28d873c566f49b477c39bb7541a22f4737bc6b153a"
    end
    on_arm do
      url "https://github.com/FollowTheProcess/spok/releases/download/v0.7.1/spok-0.7.1-linux-arm64.tar.gz"
      sha256 "35e3cdcc872d03c239b360c25c9934750582f5990216118758e8cd2e94932ca5"
    end
  end

  conflicts_with formula: [
      "spok",
    ]

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/spok"]
    end
  end

  # No zap stanza required
end
