# This file was generated by GoReleaser. DO NOT EDIT.
cask "tag" do
  desc "The all in one semver management tool"
  homepage "https://github.com/FollowTheProcess/tag"
  version "0.9.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tag"

  on_macos do
    on_intel do
      url "https://github.com/FollowTheProcess/tag/releases/download/v0.9.1/tag-0.9.1-darwin-x86_64.tar.gz"
      sha256 "894026f2021d9c1293921734dfb1afe00b48dd6d2203a19ce0e927d81d3d2ab9"
    end
    on_arm do
      url "https://github.com/FollowTheProcess/tag/releases/download/v0.9.1/tag-0.9.1-darwin-arm64.tar.gz"
      sha256 "35cd902ee919df662f953c0d4cebc44b575bb686deec07dee63a9f07071249df"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/FollowTheProcess/tag/releases/download/v0.9.1/tag-0.9.1-linux-x86_64.tar.gz"
      sha256 "5b2c1a745be7a6c2d24919edadabfb48aacdfbdb6eaf4d773db265c31da508e0"
    end
    on_arm do
      url "https://github.com/FollowTheProcess/tag/releases/download/v0.9.1/tag-0.9.1-linux-arm64.tar.gz"
      sha256 "f5b82cb6d9f91a8573ee51001682d86b0d6c25d155bbe4ec4521561bd66e491d"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tag"]
    end
  end

  # No zap stanza required
end
