# This file was generated by GoReleaser. DO NOT EDIT.
cask "tag" do
  desc "The all in one semver management tool"
  homepage "https://github.com/FollowTheProcess/tag"
  version "0.9.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tag"

  on_macos do
    on_intel do
      url "https://github.com/FollowTheProcess/tag/releases/download/v0.9.0/tag-0.9.0-darwin-x86_64.tar.gz"
      sha256 "adde5272030b872551c65c729b497dbb3292e9566e42df6df0cd08e40e259f9e"
    end
    on_arm do
      url "https://github.com/FollowTheProcess/tag/releases/download/v0.9.0/tag-0.9.0-darwin-arm64.tar.gz"
      sha256 "e0c9d19f0bc6c775695ee70d411a711ffd86be44ba210e65ce3f1e1e5b4ae854"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/FollowTheProcess/tag/releases/download/v0.9.0/tag-0.9.0-linux-x86_64.tar.gz"
      sha256 "f4563409103452a98477659b70450a40a269b8edc60f033dc372a710728714cb"
    end
    on_arm do
      url "https://github.com/FollowTheProcess/tag/releases/download/v0.9.0/tag-0.9.0-linux-arm64.tar.gz"
      sha256 "47d21d99f165f0a840dcb7096785a67e080b87b9abb5dfacf1995265b5d75981"
    end
  end

  conflicts_with formula: [
      "tag",
    ]

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tag"]
    end
  end

  # No zap stanza required
end
