# This file was generated by GoReleaser. DO NOT EDIT.
cask "tag" do
  desc "The all in one semver management tool"
  homepage "https://github.com/FollowTheProcess/tag"
  version "0.8.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tag"

  on_macos do
    on_intel do
      url "https://github.com/FollowTheProcess/tag/releases/download/v0.8.2/tag-0.8.2-darwin-x86_64.tar.gz"
      sha256 "a2a0d737863c099690e6121dfb99984633b07b0075a8291b60a58b7dc1e40a53"
    end
    on_arm do
      url "https://github.com/FollowTheProcess/tag/releases/download/v0.8.2/tag-0.8.2-darwin-arm64.tar.gz"
      sha256 "9c3c2d4fb2d83e2af2a608a3f48a10d486aa7420360e8798677d03da2f148777"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/FollowTheProcess/tag/releases/download/v0.8.2/tag-0.8.2-linux-x86_64.tar.gz"
      sha256 "88ab49762787abc6c6b6f126821816f41af8a4c5b1e08112f24909223d4b6ddb"
    end
    on_arm do
      url "https://github.com/FollowTheProcess/tag/releases/download/v0.8.2/tag-0.8.2-linux-arm64.tar.gz"
      sha256 "1c26a5d5805b0e58a02d766488ec23a6ac85cea11d9046ec1c7d08ba526a739c"
    end
  end

  conflicts_with formula: [
      "tag",
    ]

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tag"]
    end
  end

  # No zap stanza required
end
