# This file was generated by GoReleaser. DO NOT EDIT.
cask "txtract" do
  desc "A CLI to interact with txtar archive files"
  homepage "https://github.com/FollowTheProcess/txtract"
  version "0.3.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "txtract"

  on_macos do
    on_intel do
      url "https://github.com/FollowTheProcess/txtract/releases/download/v0.3.1/txtract-0.3.1-darwin-x86_64.tar.gz"
      sha256 "087dc9d54410c98d917abd2a70a9330480e97254633eeab7f36b3fe6ea7fd97e"
    end
    on_arm do
      url "https://github.com/FollowTheProcess/txtract/releases/download/v0.3.1/txtract-0.3.1-darwin-arm64.tar.gz"
      sha256 "04de02d82cd2d6547ed57cf992d1f4dad394755f321c938d0c159d1299295739"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/FollowTheProcess/txtract/releases/download/v0.3.1/txtract-0.3.1-linux-x86_64.tar.gz"
      sha256 "5bc3652aacaba6439878b3c19b1170c20b25b20e172b998a15d2d36ed8f04a2b"
    end
    on_arm do
      url "https://github.com/FollowTheProcess/txtract/releases/download/v0.3.1/txtract-0.3.1-linux-arm64.tar.gz"
      sha256 "3c4a4e3e087f374316264b7afba91503518811de5a99467bf9bd8d43560fb1ee"
    end
  end

  conflicts_with formula: [
      "txtract",
    ]

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/txtract"]
    end
  end

  # No zap stanza required
end
