# This file was generated by GoReleaser. DO NOT EDIT.
cask "txtract" do
  desc "A CLI to interact with txtar archive files"
  homepage "https://github.com/FollowTheProcess/txtract"
  version "0.3.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "txtract"

  on_macos do
    on_intel do
      url "https://github.com/FollowTheProcess/txtract/releases/download/v0.3.2/txtract-0.3.2-darwin-x86_64.tar.gz"
      sha256 "9861147743844f2cf304cbb3bed52ef8081489c41754197d65945d4efd1cdefa"
    end
    on_arm do
      url "https://github.com/FollowTheProcess/txtract/releases/download/v0.3.2/txtract-0.3.2-darwin-arm64.tar.gz"
      sha256 "ea4ee0777e1fbb9fb8c0391fa5024acd001c30c8bac833cd94ccbef6f62acc79"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/FollowTheProcess/txtract/releases/download/v0.3.2/txtract-0.3.2-linux-x86_64.tar.gz"
      sha256 "79ef3d693e0e98c740b3a9a7b0ade9554bffc1b3036fe8c483d657c1fb668e9a"
    end
    on_arm do
      url "https://github.com/FollowTheProcess/txtract/releases/download/v0.3.2/txtract-0.3.2-linux-arm64.tar.gz"
      sha256 "a6e1c5cf00a84a8c570ef26438cf090c7c035573ec5a71ffe7e9dcf7eaf1dda3"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/txtract"]
    end
  end

  # No zap stanza required
end
