# This file was generated by GoReleaser. DO NOT EDIT.
cask "txtract" do
  desc "A CLI to interact with txtar archive files"
  homepage "https://github.com/FollowTheProcess/txtract"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "txtract"

  on_macos do
    on_intel do
      url "https://github.com/FollowTheProcess/txtract/releases/download/v0.3.0/txtract-0.3.0-darwin-x86_64.tar.gz"
      sha256 "9c9e31937001dfe8a364e101e579b63bd82c39527d67006d836070f569563a9d"
    end
    on_arm do
      url "https://github.com/FollowTheProcess/txtract/releases/download/v0.3.0/txtract-0.3.0-darwin-arm64.tar.gz"
      sha256 "4c57462b314a6bd91f135c520456dc4a8317feb8c3f79de634905592fc2acf49"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/FollowTheProcess/txtract/releases/download/v0.3.0/txtract-0.3.0-linux-x86_64.tar.gz"
      sha256 "db0eb1a600d4a0e530cad76616211bd502a99cfb9a2a013d1a86c83b359544eb"
    end
    on_arm do
      url "https://github.com/FollowTheProcess/txtract/releases/download/v0.3.0/txtract-0.3.0-linux-arm64.tar.gz"
      sha256 "27cbcb6206c3ec9bbed2ccc304f2cfa631196f00e0282752784c318fc7f0fa1b"
    end
  end

  conflicts_with formula: [
      "txtract",
    ]

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/txtract"]
    end
  end

  # No zap stanza required
end
