# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Brewtest < Formula
  desc "Trying to see how to build a rust homebrew formula in ci"
  homepage "https://github.com/FollowTheProcess/brewtest"
  url "https://github.com/FollowTheProcess/brewtest/archive/v0.0.20.tar.gz"
  sha256 "53986b790fd9f774a1ff9269a6f0ee34567aada761680c876732cb1e9c8e8ab4"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/FollowTheProcess/brewtest/releases/download/v0.0.20/brewtest-0.0.20-darwin-amd64.tar.gz"
      sha256 "b8e7f87200148585caaf3aa57a9d7155df92c7e9d249ec98e55a07347f003ac5"
    end

    on_arm do
      url "https://github.com/FollowTheProcess/brewtest/releases/download/v0.0.20/brewtest-0.0.20-darwin-arm64.tar.gz"
      sha256 "08bb3e9c12af9d76d987386a41b79edadfaf4b14ba7139de12e06f9fb58e93b7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/FollowTheProcess/brewtest/releases/download/v0.0.20/brewtest-0.0.20-linux-amd64.tar.gz"
      sha256 "0ac5c5246a42a508125f303a5c02ce6453557516a60b51c401df4647f8f9f2da"
    end
  end

  def install
    bin.install "brewtest"
  end

  test do
    #{bin}/brewtest --version
  end
end
