# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitRekt < Formula
  desc "A profoundly unhelpful git extension"
  homepage "https://github.com/FollowTheProcess/git-rekt"
  version "0.1.1"
  license "MIT License"

  on_macos do
    on_intel do
      url "https://github.com/FollowTheProcess/git-rekt/releases/download/v0.1.1/git-rekt-0.1.1-darwin-x86_64.tar.gz"
      sha256 "bda3b2c347fff3b3592f2aaf3e31241515162f5460cf9e9768dd0a337dbe66b7"

      def install
        bin.install "git-rekt"
      end
    end
    on_arm do
      url "https://github.com/FollowTheProcess/git-rekt/releases/download/v0.1.1/git-rekt-0.1.1-darwin-arm64.tar.gz"
      sha256 "90ac8d49694c3a0c1fec410d765aec01c2037949e15fbbced84cf94495a4411d"

      def install
        bin.install "git-rekt"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/FollowTheProcess/git-rekt/releases/download/v0.1.1/git-rekt-0.1.1-linux-x86_64.tar.gz"
        sha256 "2c4d6fb7db12e4cda572cc2f6a1b4cb37fe1cb80c0bf14f5cac070c853ec1e38"

        def install
          bin.install "git-rekt"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/FollowTheProcess/git-rekt/releases/download/v0.1.1/git-rekt-0.1.1-linux-arm64.tar.gz"
        sha256 "5be5d32f67556497d00902b672c290cd9d9845e083e0933ec0ee8f4701fa359a"

        def install
          bin.install "git-rekt"
        end
      end
    end
  end

  test do
    "#{bin}/git-rekt --version"
  end
end
