# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gowc < Formula
  desc "Toy clone of coreutils wc in Go"
  homepage "https://github.com/FollowTheProcess/gowc"
  version "0.1.1"
  license "MIT License"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FollowTheProcess/gowc/releases/download/v0.1.1/gowc-0.1.1-darwin-x86_64.tar.gz"
      sha256 "e3686d6650444bbcf81853b2429f6e3d2886348e55d3e6bd3f486f13bf148f2c"

      def install
        bin.install "gowc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FollowTheProcess/gowc/releases/download/v0.1.1/gowc-0.1.1-darwin-arm64.tar.gz"
      sha256 "bd81589879d159731ecf97586775c3217c219ff743506028ab28d641a04f3d51"

      def install
        bin.install "gowc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/FollowTheProcess/gowc/releases/download/v0.1.1/gowc-0.1.1-linux-x86_64.tar.gz"
      sha256 "f481e8275a37dd77abd8b77274becc6cf49b78e65906f9477f863d5c948a4cac"

      def install
        bin.install "gowc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FollowTheProcess/gowc/releases/download/v0.1.1/gowc-0.1.1-linux-arm64.tar.gz"
      sha256 "3c7777e22b83d78957ba50db40018b1820825fbe8ed56aa2ed39d021a90a20ef"

      def install
        bin.install "gowc"
      end
    end
  end

  test do
    "#{bin}/gowc -version"
  end
end
