# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gowc < Formula
  desc "Implementation of wc in Go"
  homepage "https://github.com/FollowTheProcess/gowc"
  version "0.4.0"
  license "MIT License"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FollowTheProcess/gowc/releases/download/v0.4.0/gowc-0.4.0-darwin-x86_64.tar.gz"
      sha256 "bd026e47ef264ba4a7505d5b58a2b8499824e2f2719111534a27966ed5fc7d83"

      def install
        bin.install "gowc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FollowTheProcess/gowc/releases/download/v0.4.0/gowc-0.4.0-darwin-arm64.tar.gz"
      sha256 "e2482585c583b4654333c1ffc1e6f542905270d01da517df7de8ab805b88c9a9"

      def install
        bin.install "gowc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/FollowTheProcess/gowc/releases/download/v0.4.0/gowc-0.4.0-linux-x86_64.tar.gz"
        sha256 "c789dec5921aa0f7478f342bd0cd4b3e34685ae108b30d9453ee45f798f59a4c"

        def install
          bin.install "gowc"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/FollowTheProcess/gowc/releases/download/v0.4.0/gowc-0.4.0-linux-arm64.tar.gz"
        sha256 "e8e0bf08963307ba67790f2145c2453a75a3746c034292aeb5e63306aed389f7"

        def install
          bin.install "gowc"
        end
      end
    end
  end

  test do
    "#{bin}/gowc --version"
  end
end
