# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Ignorers < Formula
  desc "Generate gitignores from the command line"
  homepage "https://github.com/FollowTheProcess/ignorers"
  url "https://github.com/FollowTheProcess/ignorers/archive/v0.1.0.tar.gz"
  sha256 "7435c02001d3dd426a286770fdf914bd578fd5d2caa287452ef9e29949c76432"
  license "Apache-2.0"

  on_macos do
  end

  on_linux do
  end

  def install
    bin.install "ig"
  end
end
