# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Py < Formula
  desc "Approximate port of Brett Cannon's python-launcher to Go."
  homepage "https://github.com/FollowTheProcess/py"
  version "0.3.1"
  license "MIT License"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FollowTheProcess/py/releases/download/v0.3.1/py_ 0.3.1-darwin_x86_64{% endraw %}.tar.gz"
      sha256 "47964d5fea27ae672d4a68816874bfab2c13872ec1105bda36bdd81924a69bce"

      def install
        bin.install "py"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FollowTheProcess/py/releases/download/v0.3.1/py_ 0.3.1-darwin_arm64{% endraw %}.tar.gz"
      sha256 "6b495fffdac579655fcc7b6f741e227777fd8b8c505112375ac0a8cb46f8d089"

      def install
        bin.install "py"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/FollowTheProcess/py/releases/download/v0.3.1/py_ 0.3.1-linux_x86_64{% endraw %}.tar.gz"
      sha256 "75a3033f74497cc42a283676996297cfb831d98b6724f4dbe319dcd12c963e5f"

      def install
        bin.install "py"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FollowTheProcess/py/releases/download/v0.3.1/py_ 0.3.1-linux_arm64{% endraw %}.tar.gz"
      sha256 "352ed84fe4d5862ee41137fc1cbc34a5686d6ac239edcc58034647b364df9012"

      def install
        bin.install "py"
      end
    end
  end

  conflicts_with "python-launcher"

  test do
    "#{bin}/py --version"
  end
end
