# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spok < Formula
  desc "It's a build system Jim, but not as we know it!"
  homepage "https://github.com/FollowTheProcess/spok"
  version "0.5.0"
  license "Apache Software License 2.0"

  on_macos do
    on_intel do
      url "https://github.com/FollowTheProcess/spok/releases/download/v0.5.0/spok-0.5.0-darwin-x86_64.tar.gz"
      sha256 "495fb4d23346fd95ef2fbf214fed1e5029b4cbf765331b159fe217120e426557"

      def install
        bin.install "spok"
      end
    end
    on_arm do
      url "https://github.com/FollowTheProcess/spok/releases/download/v0.5.0/spok-0.5.0-darwin-arm64.tar.gz"
      sha256 "f195acdedc3053a94e6aeba05d0af849c4b8ab62bdf7a51bdb7625378caed4a4"

      def install
        bin.install "spok"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/FollowTheProcess/spok/releases/download/v0.5.0/spok-0.5.0-linux-x86_64.tar.gz"
        sha256 "c412ef2613bc88fe217f11fb7fa09c60247fc4d74ca4b869fbe4dbe52f8d148d"

        def install
          bin.install "spok"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/FollowTheProcess/spok/releases/download/v0.5.0/spok-0.5.0-linux-arm64.tar.gz"
        sha256 "7cdfa310883946f863257b568f9c39989589cff62c0efe918f4289f70418bbd6"

        def install
          bin.install "spok"
        end
      end
    end
  end

  test do
    "#{bin}/spok --version"
  end
end
