# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tag < Formula
  desc "The all in one semver management tool"
  homepage "https://github.com/FollowTheProcess/tag"
  version "0.4.0"
  license "Apache Software License 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/FollowTheProcess/tag/releases/download/v0.4.0/tag-0.4.0-darwin-arm64.tar.gz"
      sha256 "6d52a95d925b1638b83df3063a5918ddd31bbe1bdb01d16dbff759f8678c52ac"

      def install
        bin.install "tag"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/FollowTheProcess/tag/releases/download/v0.4.0/tag-0.4.0-darwin-x86_64.tar.gz"
      sha256 "11781c05becbcaeaaa43d725c5d2652fc55b6258acb83193d5b8d4f84b406ce9"

      def install
        bin.install "tag"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/FollowTheProcess/tag/releases/download/v0.4.0/tag-0.4.0-linux-x86_64.tar.gz"
      sha256 "d98132fa3644b9ecd6012f1f0838be37ddf447c00a2c48e28dceb2a031c8876a"

      def install
        bin.install "tag"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/FollowTheProcess/tag/releases/download/v0.4.0/tag-0.4.0-linux-arm64.tar.gz"
      sha256 "6c09512242692c81e75fb94d455370d251c2a25a4277373635cc6acfcca10bc0"

      def install
        bin.install "tag"
      end
    end
  end

  test do
    "#{bin}/tag --version"
  end
end
