# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Txtract < Formula
  desc "A CLI to interact with txtar archive files"
  homepage "https://github.com/FollowTheProcess/txtract"
  version "0.2.1"
  license "Apache Software License 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/FollowTheProcess/txtract/releases/download/v0.2.1/txtract-0.2.1-darwin-x86_64.tar.gz"
      sha256 "b1a501e3447549507d1657e201515826d3a33868da0c9cdac8f398ca33fa571f"

      def install
        bin.install "txtract"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/FollowTheProcess/txtract/releases/download/v0.2.1/txtract-0.2.1-darwin-arm64.tar.gz"
      sha256 "0979a652713c88eb5a30f94872442b52e32069fd2aa0b5271e03d623c946c980"

      def install
        bin.install "txtract"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/FollowTheProcess/txtract/releases/download/v0.2.1/txtract-0.2.1-linux-x86_64.tar.gz"
        sha256 "a6d75e6f01f03caf0227a57024cac90ebf4d196a515f2e488675a4f16950157a"

        def install
          bin.install "txtract"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/FollowTheProcess/txtract/releases/download/v0.2.1/txtract-0.2.1-linux-arm64.tar.gz"
        sha256 "36f0354ab203ff350dba22112d27243f1f0b0a066d3834ccfcccbd22f74331fe"

        def install
          bin.install "txtract"
        end
      end
    end
  end

  test do
    "#{bin}/txtract --version"
  end
end
